account/urls.py
from django.conf.urls import url, include
from . import views
from .profile import views as profile_views
from . import forms
from django.contrib.auth.views import (
    login, 
    logout, 
    password_reset, 
    password_reset_done, 
    password_reset_confirm,
    password_reset_complete
)

app_name = 'account'



urlpatterns = [
	url(r'^login/', login, {
        'template_name': 'account/login.html',
        'authentication_form': forms.Login
        }, name = 'login'),

	url(r'^logout/$', logout, {
        'next_page': 'account:login'
        }, name = 'logout'),

	url(r'^register/$', views.register, name = 'register'),

	url(r'^profile/', include([
		url(r'^add/$', profile_views.add_profile, name = 'add_profile'),
		url(r'^$', profile_views.Profile.as_view(), name = 'profile_empty'),
		url(r'^(?P<username>[\w@.+-]+)/$', profile_views.Profile.as_view(), name = 'profile'),
    	url(r'^(?P<username>[\w@.+-]+)/edit/$', profile_views.EditProfile.as_view(), name = 'edit_profile'),
    ])),

    url(r'^change-password/$', views.change_password, name='change_password'),
    

    url(r'^reset-password/', include([
        url(r'^$', password_reset, {
            'template_name': 'account/reset_password.html',
            'post_reset_redirect': 'account:password_reset_done',
            'email_template_name': 'account/reset_password_email.html',
            'password_reset_form': forms.PasswordReset,
            }, name='reset_password'),

        url(r'^done/$', password_reset_done, {
            'template_name': 'account/reset_password_done.html'
            }, name='password_reset_done'),

        url(r'^confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {
            'template_name': 'account/reset_password_confirm.html',
            'post_reset_redirect': 'account:password_reset_complete',
            'set_password_form': forms.SetPassword,
            }, name='password_reset_confirm'),

        url(r'^complete/$', password_reset_complete,{
            'template_name': 'account/reset_password_complete.html',
            }, name='password_reset_complete'),
    ])),


]

core/urls.py
from django.conf.urls import url, include
from .search.views import Search
from .control.skill.views import AddSkill, EditSkill
from .control import views as control_views

app_name = 'core'

urlpatterns = [

	url(r'^search/', include([
		url(r'^$', Search.as_view(), name = 'search'),
		url(r'^(?:page-(?P<page>[\d]+)/)?$', Search.as_view(), name = 'search_page'),
    ])),

	url(r'^control/', include([
		url(r'^skill/add/$', AddSkill.as_view(), name = 'add_skill'),
		url(r'^skill/(?P<id>[\d]+)/edit/$', EditSkill.as_view(), name = 'edit_skill'),
 
 		url(r'^user-validation/$', control_views.user_validation, name = 'user_validation')
	])),

] 

ismdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace = 'account')),
    url(r'^', include('core.urls', namespace = 'core')),
    
    url(r'^$', views.home, name = 'home'),  
    url(r'^home/$', views.home, name = 'home'),
    url(r'^debug/$', views.debug),

    url(r'^404/$', views.e404, name = '404')
]

templates/base.html
{% load static %}
{% load l10n %}

{% localize on %}


<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>

    <title>{% block head %}ISM db{% endblock %}</title>
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Навігація</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">База студентів</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'core:search' %}">Пошук</a></li>
        {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Керування<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'core:add_skill' %}">Навички</a></li>
              
              {% if validation_permission %}
              <li><a href="{% url 'core:user_validation' %}">Неперевірені користувачі</a></li>
              {% endif %}

            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Обліковий запис<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url 'account:profile' username=user.username  %}">Профіль</a></li>
              <li><a href="{% url 'account:edit_profile' username=user.username %}">Редагувати профіль</a></li>              
              <li class="divider"></li>
              <li><a href="{% url 'account:change_password' %}">Змінити пароль</a></li>              
              <li class="divider"></li>
              <li><a href="{% url 'account:logout' %}">Вийти</a></li>
            </ul>
          </li>
        {% else %}
          <li><a href="{% url 'account:register'%}">Реєстрація</a></li>
          <li><a href="{% url 'account:login' %}">Вхід</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

    {% block body %}
    {% endblock %}

    <!-- Core Scripts - Include with every page -->
    <script src = "{% static 'js/jquery.min.js' %}"></script>
    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}

</body>

</html>
{% endlocalize %}

templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
	<div class="row">

		<div class="jumbotron">
			<h1>Hello!!!</h1>
  			<p>Ти на стартовій сторінці</p>
		</div>
	</div>
</div>
{% endblock %}